routes/compare.py
from flask import render_template, request, Blueprint, session
from services.get_spread import player
##from flask_discord import requires_authorization, DiscordOAuth2Session
from services.get_auth import auth
##discord_blueprint = DiscordOAuth2Session()
compare_blueprint = Blueprint('compare', 
                              __name__, 
                              template_folder='templates', 
                              static_folder='static')

@compare_blueprint.route('/compare', methods=['GET', 'POST'])
##@requires_authorization
#@auth.login_required
def compare():
    '''A function for building the compare page.
    Takes in available players from a flask form 
    and returns player names and total score for each team'''

    players = player()
    all_players = players.all_players()
    player_names = players.player_names()
    
    if request.method == 'POST':

        ##Use GetList to put the data 
        ##from the index template into the array
        available_players_a = request.form.getlist('available_players_a')
        available_players_b = request.form.getlist('available_players_b')
        check = any(item in available_players_a for item 
                                            in available_players_b)

        if len(available_players_a) < 5 or len(available_players_b) < 5:
            '''If available players less than 10'''
            print("Not enough players!")
            error = "*ERROR*: Please select 10 players!"
            return render_template('compare.html', 
                                   player_names = player_names, 
                                   error = error)
        elif check is True:
            '''If Player from ListA is in ListB'''
            print("You cannot have a player in both teams!")
            error = "*ERROR*: You cannot have a player in both teams!" 
            return render_template('compare.html', 
                                   player_names = player_names, 
                                   error = error)
        else:
            ##Build teams out of available players 
            ##from all_players using an if 
            team_a = []
            team_b = []
            for row in all_players: 
                if row[0] in available_players_a:
                    team_a.append((row[0] , int(row[1])))
                elif row[0] in available_players_b:
                    team_b.append((row[0] , int(row[1])))

            ##Take the first column and put names into team_a and team_b
            team_a_names = sorted([row[0] for row in team_a])
            team_b_names = sorted([row[0] for row in team_b])

            ##Take the second element of the tuple and sum
            team_a_total = sum([row[1] for row in team_a])
            team_b_total = sum([row[1] for row in team_b])
            
            ##Add vars to a session to carry into results page
            session['team_a'] = team_a_names
            session['team_b'] = team_b_names
            session['team_a_total'] = team_a_total
            session['team_b_total'] = team_b_total

            ##Return Team A and Team B to the results template
            return render_template('result.html', 
                                   teama = team_a_names, 
                                   teamb = team_b_names, 
                                   scorea = team_a_total, 
                                   scoreb = team_b_total)
    ##If request method is not POST then it must be GET 
    ##so render compare.html including player_names
    return render_template('compare.html', 
                            player_names = player_names)

routes/leaderboard.py
from flask import render_template, Blueprint
from services.get_spread import player

leaderboard_blueprint = Blueprint('leaderboard', 
                                  __name__, 
                                  template_folder='templates', 
                                  static_folder='static')

@leaderboard_blueprint.route('/leaderboard', methods=['GET'])
def leaderboard():
    '''A function for building the leaderboard page.
    Takes in leaderboard from players table 
    and returns top10 player names and scores'''

    players = player()
    leaderboard = players.leaderboard()
    
    return render_template('leaderboard.html', 
                            game_stats = leaderboard)

routes/playertotals.py
from flask import render_template, \
                request, Blueprint
from services.get_spread import player
import services.post_spread as post
from services.get_auth import auth

##discord_blueprint = DiscordOAuth2Session()
playertotals_blueprint = Blueprint('playertotals', 
                            __name__, 
                            template_folder='templates', 
                            static_folder='static')

@playertotals_blueprint.route('/playertotals', methods=['GET', 'POST'])
##@requires_authorization
#@auth.login_required
def playertotals():

    '''A function for building the playerstotal page.
    Takes in players from a flask form and the new totals'''

    players = player()

    all_players = players.all_players()
    all_player_names = []
    for name,total in all_players:
        all_player_names.append((name))

    if request.method == 'POST':
        if request.form['submit_button'] == 'Player':
            ##Use GetList to put the data 
            ##from the index template into the array
            modified_names = request.form.getlist('player_name')
            error = None
            ##Using re.match to check if score input is 2 digits
            #match_a = re.match("(^[0-9]{1,2}$)",score_input_a)
            #match_b = re.match("(^[0-9]{1,2}$)",score_input_b)
            #if match_a == None or match_b == None:
            if 2 > 3:
                '''If score is not numeric then error'''
                print("Score is not a valid input")
                error = "Score is not a valid input"
            else:
                merged_player_names = [(all_player_names[i], modified_names[i]) for i in range(0, len(all_player_names))]
                result = post.update_player_names(merged_player_names)
                ##If post successful render the post page.
                return render_template('post.html')
            ##If there was an error return the score page with error
            return render_template('playertotals.html', 
                                    player_names = all_players, 
                                    error = error)
        elif request.form['submit_button'] == 'Total':
            ##Use GetList to put the data 
            ##from the index template into the array
            modified_totals = request.form.getlist('player_total')
            error = None
            ##Using re.match to check if score input is 2 digits
            #match_a = re.match("(^[0-9]{1,2}$)",score_input_a)
            #match_b = re.match("(^[0-9]{1,2}$)",score_input_b)
            #if match_a == None or match_b == None:
            if 2 > 3:
                '''If score is not numeric then error'''
                print("Score is not a valid input")
                error = "Score is not a valid input"
            else:
                merged_player_totals = [(all_player_names[i], modified_totals[i]) for i in range(0, len(all_player_names))]
                result = post.update_player_totals(merged_player_totals)
                ##If post successful render the post page.
                return render_template('post.html')
            ##If there was an error return the score page with error
            return render_template('playertotals.html', 
                                    player_names = all_players, 
                                    error = error)
        elif request.form['submit_button'] == 'Add':
            ##Use GetList to put the data 
            add_player = request.form.get('add_player')
            error = None
            if 2 > 3:
                '''Need some validation on player name e.g Capital'''
                print("Player name is not a valid input")
                error = "Player name is not a valid input"
            else:
                print(add_player)
                result = post.add_new_player(add_player)
                ##If post successful render the post page.
                return render_template('post.html')
            ##If there was an error return the score page with error
            return render_template('playertotals.html', 
                                    player_names = all_players, 
                                    error = error)
    ##If request method is not POST then it must be GET
    return render_template('playertotals.html', 
                            player_names = all_players)

routes/score.py
from flask import render_template, request, Blueprint
##from flask_discord import requires_authorization, DiscordOAuth2Session
import services.post_spread as post
from services.get_spread import results
import re
from services.get_auth import auth

##discord_blueprint = DiscordOAuth2Session()
score_blueprint = Blueprint('score', 
                            __name__, 
                            template_folder='templates', 
                            static_folder='static')

@score_blueprint.route('/score', methods=['GET', 'POST'])
##@requires_authorization
#@auth.login_required
def score():
    '''A function for building the score page.
    Takes in this weeks score as form input from flask form
    and return update function to add score to google sheet'''

    result = results()
    teama = result.teama()
    teamb = result.teamb()
    date = result.date()
    scorea = result.scorea()
    scoreb = result.scoreb()
    coloura = result.coloura()
    colourb = result.colourb()
    coloura = "/static/"+str(coloura)+".png"
    colourb = "/static/"+str(colourb)+".png"

    if request.method == 'POST':

        ##Get score from form user input
        score_input_a = request.form.get('score_input_a')
        score_input_b = request.form.get('score_input_b')
        score_output = []
        score_output.append((score_input_a))
        score_output.append((score_input_b))

        ##Print the result to google sheets with update enabled
        error = None
        ##Using re.match to check if score input is 2 digits
        match_a = re.match("(^[0-9]{1,2}$)",score_input_a)
        match_b = re.match("(^[0-9]{1,2}$)",score_input_b)
        if scorea != "-":
            '''If there is a score then there 
            isn't a dash in scorea so don't 
            update score and display error'''
            print("Score exists already")
            error = "Score exists already"
        elif match_a == None or match_b == None:
            '''If score is not numeric then error'''
            print("Score is not a valid input")
            error = "Score is not a valid input"
        else:
            print("Updating score")
            result = post.update_score_result(score_output)
            
            ##If there is a dash then post is returned after running update
            return render_template('post.html')
        ##If there was an error return the score page with error
        return render_template('score.html', 
                               teama = teama, 
                               teamb = teamb, 
                               date = date, 
                               error = error,
                               coloura = coloura,
                               colourb = colourb)
    ##If request method is not POST then it must be GET
    return render_template('score.html', 
                           teama = teama, 
                           teamb = teamb, 
                           date = date,
                           coloura = coloura,
                           colourb = colourb)

routes/stats.py
from flask import render_template, Blueprint
from services.get_spread import results, player

stats_blueprint = Blueprint('stats', 
                            __name__, 
                            template_folder='templates', 
                            static_folder='static')

@stats_blueprint.route('/stats', methods=['GET'])
def stats():
    '''A function for building the stats page.
    Takes in game stats from google sheets 
    and return them to stats page'''

    result = results()
    players = player()
    game_stats = result.game_stats()
    player_stats = players.player_stats()

    #Fix Internal Server Error if Stats are empty
    if len(game_stats) == 0:
        print("List is Empty!")
        game_stats = ["Empty", "Empty", "Empty"]
    
    return render_template('stats.html', 
                           game_stats = game_stats, 
                           player_game_stats = player_stats)

templates/compare.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Footy Team Compare</title>
        <link rel="icon" type="image/x-icon" href="/static/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/styles.css" rel="stylesheet" />
        <!-- Tita Toggle CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/titatoggle/2.1.2/titatoggle-dist-min.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Footy App - Manual</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('index.index') }}">Automatic</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('compare.compare') }}">Manual</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('leaderboard.leaderboard') }}">Leaderboard</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('stats.stats') }}">Stats</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('score.score') }}">Score</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('playertotals.playertotals') }}">Totals</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Projects-->
        <section class="projects-section bg-light" id="projects">
            <div class="container">
                <!-- Featured Project Row-->
                <div class="row align-items-center no-gutters mb-4 mb-lg-5">
                    <div class="col-xl-8 col-lg-7">
                        <div class="featured-text text-center text-center">
                            <form class="text-white-50 mx-auto mt-2 mb-5" method="POST" action="/compare">
                                <table class="mx-auto text-lg-left" style="width: 50%">
                                    <colgroup>
                                        <col span="1" style="width: 20%;">
                                        <col span="1" style="width: 30%;">
                                    </colgroup>
                                    <h2>Choose <span class="compatotalchecked">5</span> players for Team A:</h2>
                                    {% if error %}
                                    <div class="tool_tip"><h2> {{ error }} </h2></div>
                                    {% endif %}
                                    {% for name, playing in player_names %}
                                    <tr class="form-check checkbox-slider--default">
                                        <td><label><input class="compa-single-checkbox" type="checkbox" name="available_players_a" value="{{ name }}"><span>{{ name }}</span></label></td>
                                    </tr>
                                    {% endfor %}
                                </table>
                                <table class="mx-auto text-lg-left" style="width: 50%">
                                    <colgroup>
                                        <col span="1" style="width: 20%;">
                                        <col span="1" style="width: 30%;">
                                    </colgroup>
                                    <h2>Choose <span class="compbtotalchecked">5</span> players for Team B:</h2>
                                    {% for name, playing in player_names %}
                                    <tr class="form-check checkbox-slider--default">
                                        <td><label><input class="compb-single-checkbox" type="checkbox" name="available_players_b" value="{{ name }}"><span>{{ name }}</span></label></td>
                                    </tr>
                                    {% endfor %}
                                </table>
                                <input class="btn btn-primary js-scroll-trigger" type="submit">
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50">
            <div class="container">Copyright © RichardBignell.co.uk 2021</div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="/static/scripts.js"></script>
    </body>
</html>

templates/leaderboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Footy Team App</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/static/styles.css" rel="stylesheet" />
    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 7px;
      }
    </style>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Footy App - Top10</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('index.index') }}">Automatic</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('compare.compare') }}">Manual</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('leaderboard.leaderboard') }}">Leaderboard</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('stats.stats') }}">Stats</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('score.score') }}">Score</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('playertotals.playertotals') }}">Totals</a></li>
                      </ul>
                </div>
            </div>
        </nav>
        <!-- Projects-->
        <section class="projects-section bg-light" id="projects">
            <div class="container">
                <!-- Featured Project Row-->
                <div class="row align-items-center no-gutters mb-4 mb-lg-5">
                  <div class="col-xl-8 col-lg-7">
                      <div class="text-white-50 text-lg-left">
                          <h1>Leaderboard:</h1>
                          <h3>W(3)/D(1)/L(0)</h3>
                          <div class="text-pre">
                          <p>
                            <table>
                              <tr>
                                <th>Rank</th>
                                <th>Name</th>
                                <th>Score</th>
                              </tr>
                              {% for name, score in game_stats %}
                              <tr>
                                <td>{{ loop.index }}</td>
                                <td>{{ name }}</td>
                                <td>{{ score }}</td>
                              </tr>
                              {% endfor %}
                            </table>
                          </p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50">
            <div class="container">Copyright © RichardBignell.co.uk 2021</div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="/static/scripts.js"></script>
    </body>
</html>

templates/playertotals.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Footy Team App</title>
        <link rel="icon" type="image/x-icon" href="/static/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Tita Toggle CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/titatoggle/2.1.2/titatoggle-dist-min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Footy App - Automatic</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('index.index') }}">Automatic</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('compare.compare') }}">Manual</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('leaderboard.leaderboard') }}">Leaderboard</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('stats.stats') }}">Stats</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('score.score') }}">Score</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ url_for('playertotals.playertotals') }}">Totals</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Projects-->
        <section class="projects-section bg-light" id="projects">
            <div class="container">
                <!-- Featured Project Row-->
                <div class="row align-items-center no-gutters mb-4 mb-lg-5">
                    <div class="col-xl-8 col-lg-7">
                        <div class="featured-text text-center text-center">
                            <form class="text-white-50 mx-auto mt-2 mb-5" method="POST" action="/playertotals">
                                <table class="mx-auto text-lg-left" style="width: 50%">
                                    <colgroup>
                                        <col span="1" style="width: 20%;">
                                        <col span="1" style="width: 30%;">
                                    </colgroup>
                                    <h2>Update Player Totals:</h2>
                                    {% if error %}
                                    <div class="tool_tip"><h2> {{ error }} </h2></div>
                                    {% endif %}
                                    <table>
                                        <tr>
                                          <th>Name</th>
                                          <th>Total</th>
                                        </tr>
                                        {% for name, total in player_names %}
                                        <tr>
                                          <td><input class="form-control" type="text" id="player_name" name="player_name" value="{{ name }}"></td>
                                          <td><input class="form-control" type="text" id="player_total" name="player_total" value="{{ total }}"></td>
                                        </tr>
                                        {% endfor %}
                                      </table>
                                </table>
                                <input class="btn btn-primary js-scroll-trigger" type="submit" name="submit_button" value="Player">
                                <input class="btn btn-primary js-scroll-trigger" type="submit" name="submit_button" value="Total">
                                <br>
                                <br>
                                <h2>Add New Player:</h2><input class="form-control" type="text" id="add_player" name="add_player">
                                <input class="btn btn-primary js-scroll-trigger" type="submit" name="submit_button" value="Add">
                                <br>
                                <br>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50">
            <div class="container">Copyright © RichardBignell.co.uk 2021</div>
        </footer>
        <!-- Javascript Footer-->
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="/static/scripts.js"></script>
    </body>
</html>